name = "wine-tasting-api"
main = "src/index.js"
compatibility_date = "2024-09-29"

# Run cleanup every 12 hours to mark stale events as inactive
[triggers]
crons = ["0 */12 * * *"]

# Local development database
[[d1_databases]]
binding = "wine_events"
database_name = "wine-events"
database_id = "4e98dae0-7418-4871-98c5-a25203b059ca"

[vars]
FRONTEND_URL = "https://wine.tobiasbay.me"

routes = [
  { pattern = "api.wine.tobiasbay.me/*", zone_name = "tobiasbay.me" }
]

[env.production]
name = "wine-tasting-api"

[[env.production.d1_databases]]
binding = "wine_events"
database_name = "wine-events"
database_id = "4e98dae0-7418-4871-98c5-a25203b059ca"
